spring:
  elasticsearch:
    rest:
      uris: http://101.42.137.36:9200
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://101.42.137.36:3306/fmmall?characterEncoding=utf-8
      username: root
      password: 1111
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 7001
    host: 101.42.137.36
    database: 0
    password:
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.qfedu.fmmall.entity

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error

redisson:
  addr:
    singleAddr:
      host: redis://47.96.11.185:7001
      password: qfedu123
      database: 0